version: "3.1"

services:
  odoo:
    image: odoo:18
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons    # módulos personalizados en ./addons
      - ./odoo.conf:/etc/odoo/odoo.conf  # archivo config
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - ./postgresql:/var/lib/postgresql/data

volumes:
  pg_data:
